[tool.poetry]
name = "pySigma-backend-powershell"
version = "0.1.0"
description = "(OrderedDict([('target_name', 'PowerShell'), ('backend_package_name', 'powershell'), ('backend_name', 'PowerShell'), ('backend_class_name', 'PowerShellBackend'), ('package_type', 'backend'), ('package_name', 'pySigma-backend-powershell'), ('package_description', 'pySigma PowerShell Backend'), ('author', 'Victor Fernandez III'), ('email', '@cyberphor'), ('license', 'MIT'), ('github_account', 'cyberphor'), ('test_badge', 'false'), ('coverage_badge', 'false'), ('coverage_gist', 'GitHub Gist identifier containing coverage badge JSON expected by shields.io.'), ('status_badge', 'false'), ('status', 'pre--release-orange'), ('additional_output_formats', 'False'), ('output_formats', 'format1,format2'), ('_template', 'https://github.com/SigmaHQ/cookiecutter-pySigma-backend.git'), ('_output_dir', 'C:\\Users\\Victor\\Documents\\GitHub')]), Undefined)"
authors = ["Victor Fernandez III <@cyberphor>"]
license = "MIT"
repository = "https://github.com/cyberphor/pySigma-backend-powershell"
packages = [
    { include = "sigma" }
]

[tool.poetry.dependencies]
python = "^3.8"
pysigma = "^0.7.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
coverage = "^6.4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
